name: Deploy

on:
  push:
    branches: [main]

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and test
        uses: actions/checkout@v2
      - run: |
          yarn install
          yarn lint:check

  build:
    runs-on: ubuntu-latest
    needs:
      - lint-check

    steps:
      - name: Build
        uses: actions/checkout@v2
      - run: |
          yarn install
          yarn build

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          rm: true
          source: "."
          target: "/apps/commitzero-blog"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            exec bash
            cd /apps/commitzero-blog
            pm2 delete commitzero-blog
            pm2 start yarn --name "commitzero-blog" -- start